routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['as' => 'users.'], function () {
    Route::get('/', 'UsersController@index')->name('index');
    Route::any('/add', 'UsersController@add')->name('add');
    Route::any('/edit/{id}', 'UsersController@edit')->name('edit');
    Route::get('/show/{id}', 'UsersController@show')->name('show');
    Route::any('/delete/{id}', 'UsersController@delete')->name('delete');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

/**
 * Class User
 * @package App
 *
 * @property $name
 * @property $email
 * @property $password
 */
class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\UsersRepository;
use App\Service\UserService;
use App\User;
use Illuminate\Http\Request;

/**
 * Class UsersController
 * @package App\Http\Controllers
 */
class UsersController extends Controller
{
    /** @var UsersRepository */
    private $userRepository;
    /** @var UserService */
    private $userService;

    public function __construct(UsersRepository $usersRepository, UserService $userService)
    {
        $this->userRepository = $usersRepository;
        $this->userService = $userService;
    }

    public function index()
    {
        $users = $this->userRepository->model()->orderBy('id')->get();
        return view('users.index', [
            'users' => $users
        ]);
    }

    public function add(Request $request)
    {
        if ($request->post()) {
            $this->userService->save($request);

            return redirect()->action('UsersController@index');
        }

        return view('users.add');
    }

    public function edit(Request $request, $id)
    {
        $user = $this->userRepository->find($id);
        if ($request->post()) {
            $this->userService->save($request, $id);

            return redirect()->action('UsersController@index');
        }

        return view('users.edit', [
            'user' => $user
        ]);
    }

    public function show($id)
    {
        $user = $this->userRepository->find($id);
        return view('users.show', [
            'user' => $user
        ]);
    }

    public function delete($id)
    {
        $this->userRepository->delete($id);
        return redirect()->action('UsersController@index');
    }
}

resources/views/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ env('APP_NAME') }}</title>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    @yield('styles')
</head>
<body>
    @yield('content')
    @yield('scripts')
</body>
</html>

resources/views/users/add.blade.php
@extends('master')

@section('content')
    <h1>Add User</h1>
    <hr>
    {!! Form::open(['method' => 'post']) !!}
        @include('users.blocks.form')
    {!! Form::close() !!}
@endsection

resources/views/users/blocks/form.blade.php
<label for="name">Name:</label>
{!! Form::text('name', null, ['class' => 'form-control']) !!}<br><br>

<label for="email">Email:</label>
{!! Form::email('email', null, ['class' => 'form-control']) !!}<br><br>

<label for="password">Password:</label>
{!! Form::password('password', ['class' => 'form-control']) !!}<br><br>

<button type="submit">Submit</button>

resources/views/users/edit.blade.php
@extends('master')

@section('content')
    <h1>Edit User</h1>
    <hr>
    {!! Form::model($user, ['method' => 'post']) !!}
        @include('users.blocks.form')
    {!! Form::close() !!}
@endsection

resources/views/users/index.blade.php
@extends('master')
@php
    /** @var \App\User[] $users */
@endphp

@section('content')

    <h1>Users</h1>
    <a href="{{ route('users.add') }}">Add User</a>
    <hr>

    <table data-table-theme="default zebra">
        <thead>
        <tr>
            <th width="35%">User</th>
            <th width="35%">Email</th>
            <th width="30%">&nbsp;</th>
        </tr>
        </thead>

        @foreach($users as $user)
            <tbody>
            <tr>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>
                    <a href="{{ route('users.edit', ['id' => $user->id]) }}">Edit</a>
                    <a href="{{ route('users.show', ['id' => $user->id]) }}">Show</a>
                    <a href="{{ route('users.delete', ['id' => $user->id]) }}" onclick="if(!confirm('Delete {{$user->id}}?')) return false;">Delete</a>
                </td>
            </tr>
            </tbody>
        @endforeach
    </table>

@endsection

resources/views/users/show.blade.php
@extends('master')
@php
    /** @var \App\User $user */
@endphp

@section('content')
    <h1>Show User</h1>
    <hr>
    <table data-table-theme="default zebra">
        <tr>
            <td><b>Name:</b> {{ $user->name }}</td>
        </tr>
        <tr>
            <td><b>Email:</b> {{ $user->email }}</td>
        </tr>
        <tr>
            <td><b>Created at:</b> {{ $user->created_at }}</td>
        </tr>
        <tr>
            <td><b>Updated at:</b> {{ $user->updated_at }}</td>
        </tr>
    </table>
@endsection